services:

  registry:
    image: 'registry:2'

  engine:
      image: 'quay.io/powercloud/docker-ce-build@sha256:b00a990424d9bb4d3d4bf76f64ee2cf31992d1a9364e8cbf33c371380efeebe3'
      privileged: true
      environment:
        - DOCKER_TLS_CERTDIR=

  notary-server:
      build:
        context: ./testdata
        dockerfile: Dockerfile.notary-server
      ports:
        - 4443:4443
      command: ['notary-server', '-config=/fixtures/notary-config.json']

  evil-notary-server:
      build:
        context: ./testdata
        dockerfile: Dockerfile.evil-notary-server
      ports:
        - 4444:4443
      command: ['notary-server', '-config=/fixtures/notary-config.json']
